export const ERROR_CODES = {
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_INPUT: "INVALID_INPUT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  NO_TOKEN_PROVIDED: "NO_TOKEN_PROVIDED",
  INVALID_TOKEN: "INVALID_TOKEN",
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
  MODULE_NOT_FOUND: "MODULE_NOT_FOUND",
  LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
  CANNOT_DELETE_OWN_ACCOUNT: "CANNOT_DELETE_OWN_ACCOUNT",
  MISSING_QUERY_PARAM: "MISSING_QUERY_PARAM",
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
